import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Eye, EyeOff, CheckCircle2 } from "lucide-react";
import { api } from "@/shared/api/client";
import { useAuth } from "@/features/session/AppContext";

function accessTokenFromHash() { const params = new URLSearchParams(window.location.hash.replace(/^#/, "")); return params.get("access_token") || ""; }
export default function ResetPassword() {
  const { logout } = useAuth();
  const navigate = useNavigate(); const token = useMemo(accessTokenFromHash, []);
  useEffect(() => { if (window.location.hash) window.history.replaceState(null, "", window.location.pathname); }, []);
  const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError("");setMessage("");if(!token)return setError("This reset link is missing or expired. Request a new one from Forgot password.");if(password.length<8)return setError("Password must be at least 8 characters");if(password!==confirm)return setError("Passwords do not match");setLoading(true);try{const d=await api<any>("/auth/reset-password",{method:"POST",body:JSON.stringify({accessToken:token,password})});await logout();setMessage(d.message);setTimeout(()=>navigate("/login"),1800)}catch(e:any){setError(e.message||"Unable to reset password")}finally{setLoading(false)}}
  return <div className="min-h-[calc(100dvh-4rem)] bg-transparent flex items-center justify-center p-5"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.06] backdrop-blur p-8 shadow-2xl"><h1 className="text-3xl font-bold text-white">Set a new password</h1><p className="text-white/40 text-sm mt-2">Choose a new password for your LD SERVICE ZONE account.</p>{error&&<div role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-500/10 text-red-300 px-4 py-3 text-sm">{error}</div>}{message&&<div role="status" className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-500/10 text-emerald-300 px-4 py-3 text-sm flex gap-2"><CheckCircle2 size={16}/>{message}</div>}<form onSubmit={submit} className="mt-6 space-y-4"><div className="relative"><input aria-label="New password" autoComplete="new-password" required minLength={8} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password (8+ characters)" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3.5 pr-11 text-white outline-none focus:border-blue-500/60"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Hide password":"Show password"} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><input aria-label="Confirm new password" autoComplete="new-password" required minLength={8} type={show?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3.5 text-white outline-none focus:border-blue-500/60"/><button disabled={loading||!!message} className="w-full rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 py-3.5 text-white font-semibold disabled:opacity-60">{loading?"Updating…":"Update Password"}</button></form><p className="text-center text-white/40 text-sm mt-6"><Link to="/login" className="text-blue-400">Back to login</Link></p></div></div>
}
