import { useEffect, useState } from "react";
import { api } from "../../lib/api";

const STATES=["Andhra Pradesh","Assam","Bihar","Chhattisgarh","Delhi","Gujarat","Haryana","Himachal Pradesh","Jammu & Kashmir","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Odisha","Punjab","Rajasthan","Tamil Nadu","Telangana","Uttar Pradesh","Uttarakhand","West Bengal"];
const empty={fullName:"",dob:"",aadhaar:"",pan:"",address:"",city:"",state:"",pincode:"",bankAccount:"",ifsc:"",accountHolder:""};

export default function ProfilePage(){
 const [user,setUser]=useState<any>(null); const [wallet,setWallet]=useState<any>(null); const [logs,setLogs]=useState<any[]>([]); const [kyc,setKyc]=useState<any>(empty); const [files,setFiles]=useState<Record<string,File>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{Promise.all([api<any>("/auth/me"),api<any>("/wallet"),api<any>("/auth/activity"),api<any>("/kyc")]).then(([u,w,l,k])=>{setUser(u.user);setWallet(w.wallet);setLogs(l.logs||[]);setKyc({...empty,...k.kyc,aadhaar:k.kyc?.aadhaar||"",pan:k.kyc?.pan||"",bankAccount:k.kyc?.bankAccount||""})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const update=(key:string,v:string)=>setKyc((x:any)=>({...x,[key]:v}));
 const submit=async(e:any)=>{e.preventDefault();setSaving(true);setMessage("");setError("");try{const documents:any={}; for(const [name,file] of Object.entries(files)){documents[name]={fileName:file.name,mimeType:file.type,data:await toDataUrl(file)}}; const r=await api<any>("/kyc",{method:"POST",body:JSON.stringify({...kyc,documents})}); setMessage(r.message); const me=await api<any>("/auth/me");setUser(me.user); setFiles({});}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 if(loading)return <div className="p-8 text-[#94A3B8]">Loading profile & KYC…</div>;
 const verified=user?.kycStatus==="verified";
 return <div className="p-5 sm:p-6 space-y-5 max-w-[1050px]">
  <div><h1 className="font-display text-2xl font-extrabold">Profile & KYC</h1><p className="text-[#94A3B8] text-sm">Your account information and your own KYC verification details.</p></div>
  <div className="bg-[#07111F] rounded-2xl p-6 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display font-bold text-xl">{user?.name||"—"}</h2><p className="text-white/60 text-sm">{user?.businessName||"—"}</p></div><span className={`px-3 py-1.5 rounded-full text-xs font-bold ${verified?"bg-emerald-400/15 text-emerald-300":user?.kycStatus==="pending"?"bg-amber-400/15 text-amber-300":"bg-red-400/15 text-red-300"}`}>KYC: {user?.kycStatus||"required"}</span></div><div className="grid grid-cols-2 gap-3 mt-5"><div className="bg-white/10 rounded-xl p-3"><b>₹{Number(wallet?.balance||0).toLocaleString("en-IN")}</b><p className="text-[10px] text-white/50">Wallet</p></div><div className="bg-white/10 rounded-xl p-3"><b>{user?.email||"—"}</b><p className="text-[10px] text-white/50">Login email</p></div></div></div>
  <div className="bg-white rounded-2xl border border-[#E2E8F0] p-6"><h3 className="font-semibold mb-4">Account details</h3><div className="grid sm:grid-cols-2 gap-4">{[["Full Name",user?.name],["Business Name",user?.businessName],["Mobile",user?.mobile],["Email",user?.email],["Role",user?.role],["Status",user?.status]].map(([l,v])=><div key={String(l)}><label className="block text-xs text-[#94A3B8] mb-1">{l}</label><input readOnly value={String(v||"")} className="w-full px-4 py-3 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC]"/></div>)}</div></div>
  <div className="bg-white rounded-2xl border border-[#E2E8F0] p-6"><div className="flex items-start justify-between gap-4 mb-5"><div><h3 className="font-semibold text-lg">KYC Verification — Required</h3><p className="text-sm text-[#94A3B8]">This form belongs to the currently logged-in user. Submit your own identity, address and bank documents.</p></div></div>{message&&<div className="mb-4 p-3 rounded-xl bg-emerald-50 text-emerald-700 text-sm">{message}</div>}{error&&<div className="mb-4 p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}
  <form onSubmit={submit} className="space-y-6">
   <section><h4 className="font-semibold mb-3">Personal identity</h4><div className="grid sm:grid-cols-2 gap-4"><Field label="Full legal name" value={kyc.fullName} onChange={v=>update("fullName",v)} disabled={verified}/><Field label="Date of birth" type="date" value={kyc.dob} onChange={v=>update("dob",v)} disabled={verified}/><Field label="Aadhaar number" value={kyc.aadhaar} maxLength={12} onChange={v=>update("aadhaar",v.replace(/\D/g,""))} disabled={verified}/><Field label="PAN number" value={kyc.pan} maxLength={10} onChange={v=>update("pan",v.toUpperCase())} disabled={verified}/></div></section>
   <section><h4 className="font-semibold mb-3">Address</h4><div className="grid sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><Field label="Full address" value={kyc.address} onChange={v=>update("address",v)} disabled={verified}/></div><Field label="City" value={kyc.city} onChange={v=>update("city",v)} disabled={verified}/><label className="text-xs font-medium text-[#475569]">State<select value={kyc.state} onChange={e=>update("state",e.target.value)} disabled={verified} className="mt-1 w-full px-4 py-3 rounded-xl border border-[#E2E8F0] bg-white"><option value="">Select state</option>{STATES.map(s=><option key={s}>{s}</option>)}</select></label><Field label="PIN code" value={kyc.pincode} maxLength={6} onChange={v=>update("pincode",v.replace(/\D/g,""))} disabled={verified}/></div></section>
   <section><h4 className="font-semibold mb-3">Bank details for settlements</h4><div className="grid sm:grid-cols-2 gap-4"><Field label="Account holder name" value={kyc.accountHolder} onChange={v=>update("accountHolder",v)} disabled={verified}/><Field label="Bank account number" value={kyc.bankAccount} onChange={v=>update("bankAccount",v)} disabled={verified}/><Field label="IFSC code" value={kyc.ifsc} maxLength={11} onChange={v=>update("ifsc",v.toUpperCase())} disabled={verified}/></div></section>
   <section><h4 className="font-semibold mb-3">Required documents</h4><div className="grid sm:grid-cols-2 gap-4">{[["panCard","PAN card"],["aadhaarCard","Aadhaar card"],["selfie","Live selfie / photo"],["bankProof","Bank proof / cancelled cheque"]].map(([k,l])=><label key={k} className="rounded-xl border border-dashed border-[#CBD5E1] p-4 text-sm"><span className="block font-medium mb-2">{l}</span><input type="file" accept="image/*,application/pdf" disabled={verified} onChange={e=>setFiles(x=>({...x,[k]:e.target.files?.[0] as File}))}/>{files[k]&&<span className="text-xs text-emerald-600 block mt-2">{files[k].name}</span>}</label>)}</div><p className="text-xs text-[#94A3B8] mt-2">Maximum 5 MB per document. Documents are stored under your account and are accessible only through authenticated routes.</p></section>
   {!verified&&<button disabled={saving} className="w-full sm:w-auto px-6 py-3 rounded-xl bg-[#1D6FE0] text-white font-semibold disabled:opacity-60">{saving?"Submitting KYC…":"Submit KYC for verification"}</button>}
  </form></div>
  <div className="bg-white rounded-2xl border border-[#E2E8F0] p-6"><h3 className="font-semibold mb-4">Recent account activity</h3>{logs.length?logs.map(l=><div key={l.id} className="py-3 border-b border-[#F1F4F9] text-sm"><b>{l.action}</b><span className="text-[#94A3B8]"> · {new Date(l.createdAt).toLocaleString()}</span></div>):<p className="text-sm text-[#94A3B8]">No activity recorded.</p>}</div>
 </div>
}
function Field({label,value,onChange,type="text",disabled=false,maxLength}:{label:string;value:string;onChange:(v:string)=>void;type?:string;disabled?:boolean;maxLength?:number}){return <label className="text-xs font-medium text-[#475569]">{label}<input required type={type} value={value||""} maxLength={maxLength} disabled={disabled} onChange={e=>onChange(e.target.value)} className="mt-1 w-full px-4 py-3 rounded-xl border border-[#E2E8F0] bg-white disabled:bg-[#F8FAFC]"/></label>}
async function toDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
